ALTER TABLE "links" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
DROP SEQUENCE "links_id_seq";--> statement-breakpoint
ALTER TABLE "links" ALTER COLUMN "id" SET DATA TYPE integer USING "id"::integer;--> statement-breakpoint
ALTER TABLE "links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('links_id_seq'::regclass, COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM "links";